kind: pipeline 
name: eks_cluster_fargate_terraform

steps:
- name: terraform init
  image: hashicorp/terraform:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    TF_VAR_env: devel
  commands:
    - terraform init
  when:
    event:
      - pull_request
      - push
- name: terraform plan
  image: hashicorp/terraform:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    TF_VAR_env: devel
  commands:
    - terraform plan
  when:
    event:
      - pull_request
      - push
- name: terraform apply
  image: centos:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    TF_VAR_env: devel
  commands:
    - yum install wget -y
    - yum install unzip -y
    - wget https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip
    - unzip terraform_0.14.5_linux_amd64.zip
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
    - echo "$(<kubectl.sha256) kubectl" | sha256sum --check
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - ./terraform apply -auto-approve
  when:
    event:
      - pull_request
      - push
- name: terraform destroy
  image: hashicorp/terraform:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    TF_VAR_env: devel
  commands:
    - terraform destroy -auto-approve
  when:
    event:
      - pull_request
      - push
